export const WORKFLOW_VERSION_STATUS = {
  VALIDATING: 'validating',
  VALIDATED: 'validated',
  CLARIFYING: 'clarifying',
  BUILDING: 'building',
  PENDING_USER_APPROVAL: 'pending_user_approval',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  FAILED: 'failed',
  ARCHIVED: 'archived',
} as const;

export type WorkflowVersionStatus =
  (typeof WORKFLOW_VERSION_STATUS)[keyof typeof WORKFLOW_VERSION_STATUS];

export const WORKFLOW_MESSAGE_ROLE = {
  USER: 'user',
  ASSISTANT: 'assistant',
} as const;

export type WorkflowMessageRole =
  (typeof WORKFLOW_MESSAGE_ROLE)[keyof typeof WORKFLOW_MESSAGE_ROLE];

export const DRAFT_STATUSES: WorkflowVersionStatus[] = [
  WORKFLOW_VERSION_STATUS.VALIDATING,
  WORKFLOW_VERSION_STATUS.VALIDATED,
  WORKFLOW_VERSION_STATUS.CLARIFYING,
  WORKFLOW_VERSION_STATUS.BUILDING,
  WORKFLOW_VERSION_STATUS.PENDING_USER_APPROVAL,
];

export const TERMINAL_STATUSES: WorkflowVersionStatus[] = [
  WORKFLOW_VERSION_STATUS.APPROVED,
  WORKFLOW_VERSION_STATUS.REJECTED,
  WORKFLOW_VERSION_STATUS.FAILED,
  WORKFLOW_VERSION_STATUS.ARCHIVED,
];

export const MESSAGE_ALLOWED_STATUSES: WorkflowVersionStatus[] = [
  WORKFLOW_VERSION_STATUS.VALIDATING,
  WORKFLOW_VERSION_STATUS.VALIDATED,
  WORKFLOW_VERSION_STATUS.CLARIFYING,
  WORKFLOW_VERSION_STATUS.PENDING_USER_APPROVAL,
];

export const BUILDING_POLL_INTERVAL_MS = 1000;
export const BUILDING_POLL_TIMEOUT_MS = 60000;
